import Head from 'next/head'
import React, { FC } from 'react'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'

/*High order component*/

export const MainLayout=({children}) => {
    return (
        <div className={styles.container}>
          <Navbar/>
    
          <Head>
            <title>Contact-Ronny</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        
            {/**El children pude recibir JSX o un arreglo de JSX.  */}
          <main className={styles.main}>
                {children}
    
           
          </main>
    
        </div>
      )
}
